delivery_tracker/urls.py
from django.conf.urls import url
from django.shortcuts import redirect

from delivery_tracker import views


urlpatterns = [
    # TODO: convention trailing slash means no modification to DB
    url(r'^$', views.home_page, name='home_page'),
    url(r'^tracker/register/$', views.register, name='register'),
    url(r'^tracker/finish_registration/(?P<slug>\w+)/$',
        views.finish_registration, name='finish_registration'),
    url(r'^tracker/forgot_password/$',
        views.forgot_password, name='forgot_password'),
    url(r'^tracker/login/$',
        views.user_login, name='login'),
    url(r'^tracker/logout/$',
        views.user_logout, name='logout'),

    url(r'^tracker/cabinet/$',
        views.cabinet, name='cabinet'),
    url(r'^tracker/cabinet/personal_data/$',
        views.personal_data, name='cabinet_personal_data'),
    url(r'^tracker/orders_and_bills/$',
        views.orders_and_bills, name='orders_and_bills'),
    url(r'^tracker/new_order/$', views.new_order, name='new_order'),
    url(r'^tracker/my_orders/(?P<status>\w+)$',
        views.my_orders, name='my_orders'),
    url(r'^tracker/order/(?P<order_id>\w+)/details/$',
        views.purchase_order_detail, name='order'),
    url(r'^tracker/order_from_draft$',
        views.order_from_draft, name='order_from_draft'),

    url(r'^tracker/order/(?P<order_id>\w+)/cancel$',
        views.purchase_order_cancel, name='order_cancel'),
    url(r'^tracker/order/(?P<order_id>\w+)/delete$',
        views.purchase_order_delete, name='order_delete'),
    url(r'^tracker/order/(?P<order_id>\w+)/restore$',
        views.purchase_order_restore_as_draft, name='order_restore_as_draft'),

    url(r'^tracker/ajax/my_orders/get_linked_shops/$',
        views.ajax_linked_shops, name='ajax_linked_shops'),
    url(r'^tracker/ajax/my_orders/get_linked_products/$',
        views.ajax_linked_products, name='ajax_linked_products'),
    url(r'^tracker/ajax/my_orders/get_status_log/$',
        views.ajax_status_log, name='ajax_status_log'),
    url(r'^tracker/ajax/my_orders/get_linked_bills/$',
        views.ajax_linked_bills, name='ajax_linked_bills'),
    url(r'^tracker/ajax/my_orders/get_linked_in_parcels/$',
        views.ajax_linked_incoming_parcels, name='ajax_linked_in_parcels'),
    url(r'^tracker/ajax/my_orders/get_linked_out_parcels/$',
        views.ajax_linked_outcoming_parcels, name='ajax_linked_out_parcels'),
]

eurodelivery/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'', include('delivery_tracker.urls')),
    url(r'^admin/', admin.site.urls),
]

delivery_tracker/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail


CURRENT_FEE = 5


class UserRegistrationLink(models.Model):
    created_date = models.DateTimeField()
    user = models.ForeignKey('auth.User')
    slug = models.CharField(max_length=32, unique=True)

    class Meta:
        db_table = 'user_registration_link'


PURCHASE_ORDER_STATUS = {
    'draft': 1,
    'canceled': 2,
    'ordered': 3,
    'waits_for_payment': 4,
    'in_progress': 5,
    'coming_to_storage': 6,
    'received_partially': 7,
    'received_to_stock': 8,
    'deleted': 9,
}
ARCHIVE_STATUS = (
    2,
    8,
)


class PurchaseOrderStatus(models.Model):
    # Table init
    # statuses = (
    #   "Черновик", "Отменено", "Запрошено", "Ожидает оплаты",
    #   "Заказ исполнятеся", "Ожидается послупление на склад",
    #   "Частично получено", "Получено на склад", "Удалено")
    # [PurchaseOrderStatus.objects.create(description=s) for s in statuses]
    description = models.CharField(max_length=64)

    def __str__(self):
        return str(self.id) + ': ' + self.description

    class Meta:
        db_table = 'purchase_order_status'


class PurchaseOrder(models.Model):
    user = models.ForeignKey('auth.User')
    status = models.ForeignKey(PurchaseOrderStatus)
    shipping_cost = models.FloatField(default=0)
    fee = models.FloatField(default=CURRENT_FEE)
    coupon = models.CharField(max_length=64, null=True, blank=True)
    discount = models.FloatField(default=0)
    user_comment = models.CharField(
        max_length=255, null=True, blank=True, default=''
    )
    admin_comment = models.CharField(
        max_length=255, null=True, blank=True, default=''
    )

    @property
    def product_qty(self):
        return Product.objects.filter(purchase_order=self).count()

    @property
    def complex_price(self):
        products_price = sum(
            p.sum_price for p in Product.objects.filter(purchase_order=self)
        )
        return products_price + self.shipping_cost + self.fee - self.discount

    def __str__(self):
        return 'Order id: ' + str(self.id)

    class Meta:
        db_table = 'purchase_order'


class StatusLog(models.Model):
    date_modified = models.DateTimeField(auto_now=True)
    purchase_order = models.ForeignKey(PurchaseOrder)
    status = models.ForeignKey(PurchaseOrderStatus)

    def __str__(self):
        return '%s | Заказ #%d статус: %s' % (
            self.date_modified.strftime('%Y-%m-%d %H:%M:%S'),
            self.purchase_order_id,
            self.status.description
        )

    class Meta:
        db_table = 'status_log'


@receiver(pre_save)
def order_pre_save(sender, instance, *args, **kwargs):
    if sender == PurchaseOrder:
        if not instance.id:
            # new order
            return

        new_status = instance.status
        order = PurchaseOrder.objects.get(id=instance.id)
        old_status = order.status
        if old_status != new_status:
            # send mail to admin
            send_mail(
                'Смена статуса заказа',
                'Статус заказа №%d изменился с %s на %s '
                '(пользователь %s)' % (
                    instance.id, old_status, new_status,
                    instance.user.username
                ),
                settings.EMAIL_HOST_USER,
                [User.objects.get(id=1).email, ],
                fail_silently=False,
            )
            # send mail to user
            send_mail(
                'Смена статуса заказа',
                'Статус заказа №%d изменился с %s на %s' % (
                    instance.id, old_status, new_status),
                settings.EMAIL_HOST_USER,
                [instance.user.username, ],
                fail_silently=False,
            )
            StatusLog.objects.create(
                purchase_order=order,
                status=new_status
            )


class Product(models.Model):
    purchase_order = models.ForeignKey(PurchaseOrder, blank=True, null=True)
    user = models.ForeignKey('auth.User')
    shop_link = models.CharField(max_length=1024, blank=True, null=True)
    product_link = models.CharField(max_length=1024, blank=True, null=True)
    vendor_code = models.CharField(max_length=64, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    color = models.CharField(max_length=32, blank=True, null=True)
    size = models.CharField(max_length=32, blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    discount_code = models.CharField(max_length=64, blank=True, null=True)
    discount_in_shop = models.FloatField(blank=True, null=True)
    note = models.CharField(max_length=255, blank=True, null=True)

    @property
    def sum_price(self):
        return self.quantity * self.price - self.discount_in_shop

    @property
    def shop_link_trimmed(self):
        if len(self.shop_link) >= 77:
            return self.shop_link[:77] + '...'
        return self.shop_link

    def __str__(self):
        return 'id_' + str(self.id) + ' ' + self.name

    class Meta:
        db_table = 'product'

delivery_tracker/forms.py
import re

from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    # NB: you'll need to set auth_user username to VARCHAR(75)
    username = forms.EmailField(label='Email', max_length=75)
    password = forms.CharField(widget=forms.PasswordInput())

    buf_username = None

    def clean_username(self):
        username = self.cleaned_data['username']
        self.buf_username = username
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Such user already exists")

        return username

    def clean_password(self):
        password = self.cleaned_data['password']
        if (len(password) < 6 or
                not (re.search('\d', password) and
                     re.search('[A-Za-z]', password))
            ):
            raise forms.ValidationError(
                "Password is weak. It should contain letters and numbers and "
                "be longer than 6 symbols"
            )

        return password

    def full_clean(self):
        super(UserForm, self).full_clean()
        if (self.buf_username and 'username' in self._errors and
                'at most 30' in self._errors['username']):
            del self._errors['username']
            if len(self.buf_username) > 75:
                raise forms.ValidationError(
                    "Ensure this value has at most 75 characters (it has %d)" %
                    (len(self.buf_username), )
                )


class ForgotPasswordForm(forms.Form):
    registered_email = forms.EmailField(max_length=75)


class UserInfoForm(forms.Form):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=75, required=False)

    # phone = forms.CharField(max_length=20)
    # email_notifications = forms.BooleanField()
    # documents = forms.CharField(max_length=255)

delivery_tracker/templates/delivery_tracker/new_order.html
{% extends 'delivery_tracker/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <div class="row top-offset-20">
            <div class="col-md-offset-8 col-md-3">
                <b>Здравствуйте{% if user.first_name %}, {{ user.first_name }}{% endif %}!</b>
            </div>
            <div class="col-md-1">
                <b><a href="{% url 'logout' %}">Выйти</a></b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 top-offset-20">
                <div class="header_stripe">
                    <a href="{% url 'cabinet' %}">
                        <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: white"></span> Главная
                    </a> -
                    <a href="{% url 'orders_and_bills' %}">Заказы и счета</a> -
                    <a href="{% url 'new_order' %}">Создать новый заказ</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-4 col-sm-offset-4 col-md-4 col-sm-4">
                {% for msg in messages %}
                    <b>{{ msg }}</b><br/>
                {% endfor %}

            </div>
        </div>
        <div class="row top-offset-20">
            <div class="col-md-12">
                <form id="id_order_form" action="{% url 'new_order' %}" method="post" class="form-horizontal">
                    {% csrf_token %}

                    <div class="row">
                        <div class="order_product_header">
                            <div class="order_product_header_cell">Магазин</div>
                            <div class="order_product_header_cell">Ссылка на товар*</div>
                            <div class="order_product_header_cell">Артикул</div>
                            <div class="order_product_header_cell">Название товара</div>
                            <div class="order_product_header_cell">Цвет*</div>
                            <div class="order_product_header_cell">Размер*</div>
                            <div class="order_product_header_cell">Количество*</div>
                            <div class="order_product_header_cell">Цена*</div>
                            <div class="order_product_header_cell">Код скидки</div>
                            <div class="order_product_header_cell">Сумма скидки*</div>
                            <div class="order_product_header_cell">Сумма*</div>
                            <div class="order_product_header_cell">Примечание</div>
                        </div>
                    </div>
                    <div id="id_product_list">
                    <div id="id_product_row_1" class="row">
                        <div class="order_product_row" style="float:left;">
                            <input id="id_shop_link_1" type="text" name="shop_link_1" class="order_product_cell" />
                            <input id="id_product_link_1" type="text" name="product_link_1" class="order_product_cell" />
                            <input id="id_vendor_code_1" type="text" name="vendor_code_1" class="order_product_cell" />
                            <input id="id_name_1" type="text" name="name_1" class="order_product_cell" />
                            <input id="id_color_1" type="text" name="color_1" class="order_product_cell" />
                            <input id="id_size_1" type="text" name="size_1" class="order_product_cell" />
                            <input id="id_quantity_1" type="text" name="quantity_1" class="order_product_cell ctrl_calc_sum" />
                            <input id="id_price_1" type="text" name="price_1" class="order_product_cell ctrl_calc_sum" />
                            <input id="id_discount_code_1" type="text" name="discount_code_1" class="order_product_cell" />
                            <input id="id_discount_in_shop_1" type="text" name="discount_in_shop_1" value="0" class="order_product_cell ctrl_calc_sum" />
                            <input id="id_sum_1" type="text" name="sum_1" disabled class="order_product_cell ctrl_product_sum" />
                            <input id="id_note_1" type="text" name="note_1" class="order_product_cell" />
                            <div id="id_delete_product_1" class="new_order_delete_product ctrl_delete_product">Удалить</div>
                        </div>
                    </div>
                    </div>
                    <div class="row top-offset-5">
                        <div id="id_add_product" class="order_new_product">+ Добавить</div>
                    </div>

                    {{ form.shipping_cost.errors }}
                    <div class="form-group top-offset-20">
                        <label for="id_shipping_cost" class="order_new_details_key">Стоимость доставки*</label>
                        <input id="id_shipping_cost" type="text" name="shipping_cost" value="{{ form.shipping_cost.value }}" class="ctrl_calc_total_sum order_new_details_value" />
                    </div>
                    {{ form.coupon.errors }}
                    <div class="form-group">
                        <label for="id_coupon" class="order_new_details_key">Код скидки на наши услуги</label>
                        <input id="id_coupon" type="text" name="coupon" value="" class="order_new_details_value" />
                    </div>
                    {{ form.discount.errors }}
                    <div class="form-group">
                        <label for="id_discount" class="order_new_details_key">Размер скидки на наши услуги*</label>
                        <input id="id_discount" type="text" name="discount" value="{{ form.discount.value }}" class="order_new_details_value ctrl_calc_total_sum" />
                    </div>
                    {{ form.user_comment.errors }}
                    <div class="form-group">
                        <label for="id_user_comment" class="order_new_details_key">Комментарий</label>
                        <input id="id_user_comment" type="text" name="user_comment" value="{{ form.user_comment.value }}" class="order_new_details_value" />
                    </div>

                    <div class="form-group">
                        <label for="id_current_fee" class="order_new_details_key">Текущий тариф</label>
                        <input id="id_current_fee" type="text" name="current_fee" value="{{ current_fee }}" disabled="1" class="order_new_details_value" />
                    </div>
                    <input id="id_max_prod_num" name="max_prod_num" type="hidden" value="1" />


                    <div class="form-group top-offset-20">
                        <label for="id_order_total" class="order_new_details_key">Итого сумма Вашего заказа:</label>
                        <input id="id_order_total" type="text" disabled value="" class="order_new_details_value" />
                    </div>
                    <div class="row" align="right" style="margin-right: 0px;">
                        <button type="submit" name="new_order_draft" class="new_order_form_btn" style="width: 185px;">Сохранить как черновик</button>
                        <button type="submit" name="new_order" class="new_order_form_btn">Заказать</button>
                        <button type="submit" name="new_order_cancel" class="new_order_form_btn">Отмена</button>
                    </div>
                </form>
            </div>

        </div>
    </div>

{% endblock %}

{% block script %}
<script>
    var current_prod_qty = 1;

    function calc_sum() {
        var product_id = this.id.substring(this.id.lastIndexOf("_")+1);
        var qty_id = '#id_quantity_' + product_id;
        var price_id = '#id_price_' + product_id;
        var discount_in_shop_id = '#id_discount_in_shop_' + product_id;
        var sum_id = '#id_sum_' + product_id;
        if ($(qty_id).val() !== undefined && $(qty_id).val() !== '' &&
                $(price_id).val() !== undefined && $(price_id).val() !== '' &&
                $(discount_in_shop_id).val() !== undefined && $(discount_in_shop_id).val() !== ''
            ) {
            var qty = parseFloat($(qty_id).val(), 10);
            var price = parseFloat($(price_id).val(), 10);
            var discount_in_shop = parseFloat($(discount_in_shop_id).val(), 10);
            if (!isNaN(qty) && !isNaN(price) && !isNaN(discount_in_shop)) {
                var sum = qty*price - discount_in_shop;
                if (sum > 0) {
                    $(sum_id).attr('value', sum);
                    calc_total_sum();
                } else {
                    $(sum_id).attr('value', 0);
                }
            }
            else {
                $(sum_id).attr('value', '');
            }
        }
        else {
            $(sum_id).attr('value', '');
        }
    }
    $(".ctrl_calc_sum").on('input', calc_sum);
    $(".ctrl_calc_total_sum").on('input', calc_total_sum);

    function delete_product() {
        var product_id = this.id.substring(this.id.lastIndexOf("_")+1);
        $('#id_product_row_'+product_id).remove();
        calc_total_sum();
    }
    $(".ctrl_delete_product").click(delete_product);

    function calc_total_sum() {
        var total_sum = 0;
        $(".ctrl_product_sum").each(function () {
            if (!isNaN($(this).val()) && $(this).val() !== '') {
                total_sum += parseFloat($(this).val(), 10);
            }
        });
        var shipping_cost = parseFloat($('#id_shipping_cost').val(), 10);
        if ($('#id_shipping_cost').val() !== '' && !isNaN(shipping_cost)) {
            total_sum += shipping_cost;
        }
        var discount = parseFloat($('#id_discount').val(), 10);
        if ($('#id_discount').val() !== '' && !isNaN(discount)) {
            total_sum -= discount;
        }

        var current_fee = parseFloat($('#id_current_fee').val(), 10);
        if ($('#id_current_fee').val() !== '' && !isNaN(current_fee)) {
            total_sum += current_fee;
        }
        if (total_sum < 0) {
            total_sum = 0;
        }
        $("#id_order_total").attr('value', total_sum);
    }

    $("#id_add_product").click(function () {
        current_prod_qty++;
        $("#id_max_prod_num").attr('value', current_prod_qty);
        var new_product = `
            <div id="id_product_row_(product_num)" class="row">
                <div class="order_product_row" style="float:left;">
                    <input id="id_shop_link_(product_num)" type="text" name="shop_link_(product_num)" class="order_product_cell" />
                    <input id="id_product_link_(product_num)" type="text" name="product_link_(product_num)" class="order_product_cell" />
                    <input id="id_vendor_code_(product_num)" type="text" name="vendor_code_(product_num)" class="order_product_cell" />
                    <input id="id_name_(product_num)" type="text" name="name_(product_num)" class="order_product_cell" />
                    <input id="id_color_(product_num)" type="text" name="color_(product_num)" class="order_product_cell" />
                    <input id="id_size_(product_num)" type="text" name="size_(product_num)" class="order_product_cell" />
                    <input id="id_quantity_(product_num)" type="text" name="quantity_(product_num)" class="order_product_cell ctrl_calc_sum" />
                    <input id="id_price_(product_num)" type="text" name="price_(product_num)" class="order_product_cell ctrl_calc_sum" />
                    <input id="id_discount_code_(product_num)" type="text" name="discount_code_(product_num)" class="order_product_cell" />
                    <input id="id_discount_in_shop_(product_num)" type="text" name="discount_in_shop_(product_num)" value="0" class="order_product_cell ctrl_calc_sum" />
                    <input id="id_sum_(product_num)" type="text" name="sum_(product_num)" disabled readonly="1" class="order_product_cell ctrl_product_sum" />
                    <input id="id_note_(product_num)" type="text" name="note_(product_num)" class="order_product_cell" />
                    <div id="id_delete_product_(product_num)" class="new_order_delete_product ctrl_delete_product">Удалить</div>
                </div>
            </div>
        `;
        new_product = new_product.replace(/\(product_num\)/g, current_prod_qty);
        $("#id_product_list").append(new_product);

        $(".ctrl_calc_sum").on('input', calc_sum);
        $(".ctrl_delete_product").click(delete_product);

    });

</script>
{% endblock %}

delivery_tracker/templates/delivery_tracker/personal_data.html
{% extends 'delivery_tracker/base.html' %}
{% load staticfiles %}

{% block content %}
    <div id="id_shadow_all"></div>
    <div class="container">
        <div class="row top-offset-20">
            <div class="col-md-offset-8 col-md-3">
                <b>Здравствуйте{% if user.first_name %}, {{ user.first_name }}{% endif %}!</b>
            </div>
            <div class="col-md-1">
                <b><a href="{% url 'logout' %}">Выйти</a></b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 top-offset-20">
                <div class="header_stripe">
                    <a href="{% url 'cabinet' %}"><span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: white"></span> Main</a> - <a href="{% url 'cabinet_personal_data' %}">Personal data</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-4 col-sm-offset-4 col-md-4 col-sm-4">
                {% for msg in messages %}
                    <b>{{ msg }}</b><br/>
                {% endfor %}

            </div>
        </div>
        <div class="row top-offset-20">
            <div class="col-md-12">
                <form id="id_login_form" action="{% url 'cabinet_personal_data' %}" method="post" class="form-horizontal">
                    {% csrf_token %}

                    <!-- Disable browser's pre population of password and so on -->
                    <input type="password" name="password" style="display: none;" />

                    {{ form.first_name.errors }}
                    <div class="form-group">
                        <label for="id_first_name" class="control-label col-sm-2">First name</label>
                        <div class="col-sm-5">
                            <input id="id_first_name" type="text" name="first_name" value="{{ form.first_name.value }}" class="form-control" />
                        </div>
                    </div>
                    {{ form.last_name.errors }}
                    <div class="form-group">
                        <label for="id_last_name" class="control-label col-sm-2">Last name</label>
                        <div class="col-sm-5">
                            <input id="id_last_name" type="text" name="last_name" value="{{ form.last_name.value }}" class="form-control" />
                        </div>
                    </div>
                    {{ form.email.errors }}
                    <div class="form-group">
                        <label for="id_email" class="control-label col-sm-2">Email</label>
                        <div class="col-sm-5">
                            <input id="id_email" type="text" name="email" value="{{ form.email.value }}" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_password" class="control-label col-sm-2">Password</label>
                        <div class="col-sm-5">
                            <input id="id_password" type="password" name="password" value="{{ masked_password }}" class="form-control" autocomplete="off" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_phone" class="control-label col-sm-2">Phone</label>
                        <div class="col-sm-5">
                            <input id="id_phone" type="text" name="phone" value="{{ form.phone.value }}" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_notifications" class="control-label col-sm-2">Send email notifications</label>
                        <div class="col-sm-5">
                            <input id="id_notifications" type="checkbox" name="email_notifications" value="{{ form.email_notifications.value }}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_verification_docs" class="control-label col-sm-2">Documents of the account verification</label>
                        <div class="col-sm-5">
                            <input id="id_verification_docs" type="text" name="documents" value="{{ form.documents.value }}" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" name="profile_changes" class="btn btn-default">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="row">
                <div class="col-md-2">
                    Addresses
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 col-md-offset-1">
                    Country
                </div>
                <div class="col-md-2">
                    Index
                </div>
                <div class="col-md-2">
                    Address
                </div>
                <div class="col-md-2">
                    Credentials of the recipient
                </div>
                <div class="col-md-2">
                    Phone of the recipient
                </div>
            </div>
        </div>
    </div>

    <div id="dialog_form">
        <p class="validate_tips"></p>

        <form id="password_form" action="{% url 'cabinet_personal_data' %}" method="post" class="form-horizontal">
            {% csrf_token %}
                <!-- Disable browser's pre population of password and so on -->
                <input type="password" name="password" style="display: none;" />

                <div class="form-group">
                    <label class="col-sm-5 control-label" for="id_old_password">Password</label>
                    <div class="col-sm-5">
                        <input type="password" name="old_password" id="id_old_password" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-5 control-label" for="id_new_password">New password</label>
                    <div class="col-sm-5">
                        <input type="password" name="new_password" id="id_new_password" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-5 control-label" for="id_confirm_new_password">Confirm new password</label>
                    <div class="col-sm-5">
                        <input type="password" name="confirm_new_password" id="id_confirm_new_password" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-1 col-sm-5">
                        <button type="submit" name="password_change" class="btn btn-default">Change password</button>
                    </div>
                    <div class="col-sm-offset-1 col-sm-5">
                        <button id="id_button_cancel_password_change" type="button" name="cancel_password_change" class="btn btn-default">Cancel</button>
                    </div>
                </div>
        </form>
    </div>
{% endblock %}

{% block script %}
<script>
    $(function() {
        var dialog, form,
        old_password = $("#id_old_password"),
        new_password = $("#id_new_password"),
        confirm_new_password = $("#id_confirm_new_password"),
        tips = $(".validateTips");

        function updateTips(t) {
            tips
                .text(t)
                .addClass("ui-state-highlight");
            setTimeout(function() {
                tips.removeClass("ui-state-highlight", 1500);
            }, 500 );
        }
        $("#dialog_form").submit(function(event) {
            if (new_password.val() !== confirm_new_password.val()) {
                alert("Пароли не совпадают");
                event.preventDefault();
            }
        });
        dialog = $("#dialog_form").dialog({
            autoOpen: false,
            width: 350,
            modal: true,
            draggable: false,
            open: function() {
                $("#id_shadow_all").show();
            },
            close: function() {
                $("#id_shadow_all").hide();
            },
            dialogClass: 'ui-widget-shadow',
        });
        $("#id_password").on("click", function() {
            dialog.dialog("open");
            $(".ui-dialog-titlebar-close").hide();
        });

        $("#id_shadow_all").click(function () {
            dialog.dialog("close");
        });
        $("#id_button_cancel_password_change").click(function () {
            dialog.dialog("close");
        });
    });
</script>
{% endblock %}